/**
 * GENERATED by scripts/measure-coverage.mjs. Do not hand-edit.
 *
 * What each of these counts, exactly, because four numbers describing "how much
 * data do you have" is how /rates ended up claiming 928 after the corpus moved.
 * Every figure here is rendered NEXT TO `measuredAt`: a count of what survives
 * the honesty filter is true on a day, not forever.
 */
export const MEASURED_COVERAGE = {
  "measuredAt": "2026-08-26",
  "publishedMetros": 928,
  "pickerServices": 39,
  "publishedPages": 36192,
  "metrosAnsweringLocally": 840,
  "metroServicePagesAnsweringLocally": 21362,
  "statesAnswering": 56,
  "duplicateVerdictConflicts": 0
} as const;
